SELECT DISTINCT
    ACCOUNT.ACCOUNT_ID AS ACCOUNT_ID,
    ACCOUNT.CUSTOMER_ID AS CUSTOMER_ID,

    PROFILE.FIRST_NAME AS FIRST_NAME,
    PROFILE.LAST_NAME AS LAST_NAME,
    PROFILE.ORG_NAME AS ORG_NAME,

    CASE
        WHEN PROFILE.CUSTOMER_TYPE = 'BUSINESS'
            THEN PROFILE.ORG_NAME
        ELSE TRIM(
            CONCAT(
                COALESCE(PROFILE.FIRST_NAME, ''),
                ' ',
                COALESCE(PROFILE.LAST_NAME, '')
            )
        )
    END AS CUSTOMER_DISPLAY_NAME,

    PROFILE.CUSTOMER_TYPE AS CUSTOMER_TYPE,

    ACCOUNT.ACCOUNT_STATUS AS ACCOUNT_STATUS,
    ACCOUNT.SERVICE_STATE AS SERVICE_STATE,
    ACCOUNT.OPEN_DATE AS ACCOUNT_OPEN_DATE

FROM __silver__.customer_account ACCOUNT

LEFT JOIN __silver__.customer_profile PROFILE
    ON PROFILE.CUSTOMER_ID = ACCOUNT.CUSTOMER_ID

WHERE ACCOUNT.ACCOUNT_STATUS = 'ACTIVE'