SELECT DISTINCT
    ACCOUNT.CUSTOMER_ID AS CUSTOMER_ID,

    SHA2(ACCOUNT.CUSTOMER_ID, ${HASH_BITS}) AS CUSTOMER_ID_ENCRYPTED,

    ACCOUNT.ACCOUNT_ID AS ACCOUNT_ID,

    PROFILE.FIRST_NAME AS FIRST_NAME,

    TRIM(
        CONCAT(
            COALESCE(PROFILE.LAST_NAME, ''),
            COALESCE(PROFILE.ORG_NAME, '')
        )
    ) AS DISPLAY_NAME,

    PROFILE.CUSTOMER_TYPE AS CUSTOMER_TYPE,

    EMAIL.EMAIL_ADDRESS AS EMAIL_ADDRESS,

    ACCOUNT.ACCOUNT_STATUS AS ACCOUNT_STATUS,

    ACCOUNT.SERVICE_STATE AS SERVICE_STATE,

    ACCOUNT.OPEN_DATE AS ACCOUNT_OPEN_DATE

FROM __silver__.customer_account ACCOUNT

LEFT JOIN __silver__.customer_profile PROFILE
    ON PROFILE.CUSTOMER_ID = ACCOUNT.CUSTOMER_ID

LEFT JOIN __silver__.customer_email_contact EMAIL
    ON EMAIL.ACCOUNT_ID = ACCOUNT.ACCOUNT_ID

WHERE ${ACCOUNT_FILTER}
  AND ${EMAIL_FILTER}