SELECT DISTINCT
    FKKVKP.VKONT AS CUSTOMER_ID,
    SHA2(FKKVKP.VKONT, 256) AS CUSTOMER_ID_ENCRYPTED,
    BUT000.NAME_FIRST AS FIRST_NAME,
    TRIM(
        CONCAT(
            COALESCE(BUT000.NAME_LAST, ''),
            COALESCE(BUT000.NAME_ORG1, '')
        )
    ) AS LAST_NAME,

    ZCC_ACCNT_EMAIL.SMTP_ADDR AS EMAIL_ADDRESS

FROM sandbox.ss_customer.araw_sapccs_FKKVKP FKKVKP

LEFT JOIN sandbox.ss_customer.araw_sapccs_BUT000 BUT000
   ON BUT000.PARTNER = FKKVKP.GPART

LEFT JOIN sandbox.ss_customer.araw_sapccs_ZCC_ACCNT_EMAIL ZCC_ACCNT_EMAIL
   ON ZCC_ACCNT_EMAIL.VKONT = FKKVKP.VKONT

WHERE ZCC_ACCNT_EMAIL.SMTP_ADDR IS NOT NULL