SELECT
    'C1' AS SOURCE_SYSTEM,
    VKONT,
    SMTP_ADDR,
    processed_time
FROM __silver__.sapeast_ZCC_ACCNT_EMAIL
WHERE SMTP_ADDR IS NOT NULL
  AND TRIM(SMTP_ADDR) <> ''

UNION ALL

SELECT
    'C2' AS SOURCE_SYSTEM,
    VKONT,
    SMTP_ADDR,
    processed_time
FROM __silver__.sapwest_ZCC_ACCNT_EMAIL
WHERE SMTP_ADDR IS NOT NULL
  AND TRIM(SMTP_ADDR) <> ''